"""Tests that SVI slice fits never imply negative total variance.

Raw SVI attains its minimum at ``a + b*sigma*sqrt(1-rho^2)``.  When that is
negative the slice dips below zero in an unquoted wing; the grid builder then
floors it and emits a near-zero implied vol, which is what the batch QC gate
rejects.  The fit is constrained so this cannot happen.
"""

import numpy as np
import pytest

from src.surface.interpolation import (
    interpolate_svi_slice,
    svi_min_variance,
    svi_raw,
)


# ── The analytic minimum ─────────────────────────────────────────────────


def test_min_variance_matches_numeric_minimum():
    a, b, rho, m, sigma = 0.02, 0.15, -0.6, 0.05, 0.12
    k = np.linspace(-20, 20, 400_001)
    assert svi_min_variance(a, b, rho, sigma) == pytest.approx(
        svi_raw(k, a, b, rho, m, sigma).min(), abs=1e-6
    )


def test_min_variance_shifts_with_level():
    base = svi_min_variance(0.0, 0.15, -0.6, 0.12)
    assert svi_min_variance(0.05, 0.15, -0.6, 0.12) == pytest.approx(base + 0.05)


def test_min_variance_is_a_when_sigma_zero():
    assert svi_min_variance(0.03, 0.15, -0.6, 0.0) == pytest.approx(0.03)


def test_min_variance_handles_rho_at_bound():
    """|rho| = 1 must not produce a NaN via sqrt of a negative."""
    assert np.isfinite(svi_min_variance(0.01, 0.2, -1.0, 0.1))
    assert np.isfinite(svi_min_variance(0.01, 0.2, 1.0, 0.1))


# ── Fitted slices stay non-negative ──────────────────────────────────────


def _smile(k, atm_var=0.04, skew=-0.05, curv=0.30):
    """A well-behaved convex total-variance smile."""
    return atm_var + skew * k + curv * k ** 2


@pytest.mark.parametrize("skew", [0.0, -0.05, -0.20, 0.10])
def test_fit_is_non_negative_for_ordinary_smiles(skew):
    k = np.linspace(-0.4, 0.2, 25)
    _, p = interpolate_svi_slice(k, _smile(k, skew=skew))
    assert svi_min_variance(p["a"], p["b"], p["rho"], p["sigma"]) >= -1e-12


def test_fit_stays_non_negative_far_outside_quoted_range():
    """The failure mode was in wings no quote covers — check well beyond."""
    k = np.linspace(-0.4, 0.2, 25)
    _, p = interpolate_svi_slice(k, _smile(k))
    wide = np.linspace(-5.0, 5.0, 2001)
    assert svi_raw(wide, **p).min() >= -1e-12


def test_fit_on_steep_short_dated_smile():
    """Short-dated slices with a steep put wing triggered the original bug."""
    k = np.linspace(-0.40, 0.20, 30)
    w = 0.0008 + 0.02 * k ** 2 - 0.010 * k          # ~1M tenor, small variance
    _, p = interpolate_svi_slice(k, w)
    assert svi_min_variance(p["a"], p["b"], p["rho"], p["sigma"]) >= -1e-12
    assert svi_raw(np.linspace(-3, 3, 1001), **p).min() >= -1e-12


def test_fit_on_asymmetric_wing_data():
    """Data present on the put side only, forcing extrapolation to the calls."""
    k = np.linspace(-0.40, -0.05, 20)
    _, p = interpolate_svi_slice(k, _smile(k))
    assert svi_raw(np.linspace(-2, 2, 1001), **p).min() >= -1e-12


def test_fit_with_noise_stays_non_negative():
    rng = np.random.default_rng(0)
    k = np.linspace(-0.4, 0.2, 40)
    w = _smile(k) * (1 + 0.05 * rng.standard_normal(k.size))
    _, p = interpolate_svi_slice(k, np.maximum(w, 1e-6))
    assert svi_min_variance(p["a"], p["b"], p["rho"], p["sigma"]) >= -1e-12


# ── The fit is still a good fit ──────────────────────────────────────────


def test_fit_still_tracks_the_data():
    """Positivity must not be bought with a badly-fitting slice."""
    k = np.linspace(-0.4, 0.2, 25)
    w = _smile(k)
    w_fit, _ = interpolate_svi_slice(k, w)
    rmse = float(np.sqrt(np.mean((w_fit - w) ** 2)))
    assert rmse < 0.01 * w.mean()


def test_fit_recovers_an_exact_svi_slice():
    """Given data generated by SVI itself, recover a near-identical slice."""
    k = np.linspace(-0.4, 0.2, 40)
    true = dict(a=0.01, b=0.12, rho=-0.5, m=0.02, sigma=0.15)
    w = svi_raw(k, **true)
    w_fit, p = interpolate_svi_slice(k, w)

    np.testing.assert_allclose(w_fit, w, atol=2e-4)
    assert svi_min_variance(p["a"], p["b"], p["rho"], p["sigma"]) >= -1e-12


def test_atm_level_is_preserved():
    """The repair must not drag the ATM level away from the data."""
    k = np.linspace(-0.4, 0.2, 25)
    w = _smile(k)
    w_fit, _ = interpolate_svi_slice(k, w)
    atm = int(np.argmin(np.abs(k)))
    assert w_fit[atm] == pytest.approx(w[atm], rel=0.05)


def test_returned_params_reproduce_returned_curve():
    k = np.linspace(-0.4, 0.2, 25)
    w_fit, p = interpolate_svi_slice(k, _smile(k))
    np.testing.assert_allclose(svi_raw(k, **p), w_fit, rtol=1e-12)


# ── Grid-level consequence ───────────────────────────────────────────────


def test_chain_with_no_prices_is_usable_when_iv_is_quoted():
    """A session with blank bid-ask but a quoted IV must not be discarded.

    Some historical sources publish a settled IV with zero bid-ask for a whole
    day.  The price column is uninformative there, not the rows bad — filtering
    on it threw away entire sessions.
    """
    import pandas as pd

    from src.surface.grid_builder import build_surface_grid

    rows = []
    for T in (0.0833, 0.25, 1.0):
        for k in np.linspace(-0.35, 0.15, 15):
            rows.append({
                "strike": 100.0 * np.exp(k), "T": T, "option_type": "call",
                "bid": 0.0, "ask": 0.0, "mid": 0.0,
                "implied_volatility_market": 0.20 + 0.3 * k ** 2,
            })
    out = build_surface_grid(pd.DataFrame(rows), spot=100.0, r=0.01)
    assert len(out) > 0
    assert (out["implied_volatility"] > 0).all()


def test_priced_rows_are_still_filtered_normally():
    """When prices are usable, a non-positive mid still drops the row."""
    import pandas as pd

    from src.surface.grid_builder import build_surface_grid

    rows = []
    for i, k in enumerate(np.linspace(-0.35, 0.15, 20)):
        rows.append({
            "strike": 100.0 * np.exp(k), "T": 0.25, "option_type": "call",
            "bid": 1.0, "ask": 1.2, "mid": 0.0 if i < 3 else 1.1,
            "implied_volatility_market": 0.20,
        })
    out = build_surface_grid(pd.DataFrame(rows), spot=100.0, r=0.01)
    assert len(out) == 17          # the three zero-mid rows are dropped


def test_empty_scatter_raises_a_clear_error():
    """Regression: this used to fail with an opaque reshape error in SciPy."""
    import pandas as pd

    from src.surface.grid_builder import _interpolate_rbf, default_k_grid, default_t_grid

    empty = pd.DataFrame(columns=["log_moneyness", "T", "implied_volatility"])
    with pytest.raises(ValueError, match="scatter points"):
        _interpolate_rbf(empty, default_k_grid(), default_t_grid())


def test_grid_has_no_floored_cells():
    """End-to-end: a built grid must contain no near-zero implied vols.

    A floored cell shows up as sqrt(1e-8 / T), i.e. ~3e-4 — the exact symptom
    the batch QC gate was catching.
    """
    import pandas as pd

    from src.surface.grid_builder import interpolate_to_grid

    rows = []
    for T in (0.0833, 0.25, 0.5, 1.0, 2.0):
        for k in np.linspace(-0.40, 0.20, 25):
            iv = np.sqrt(max(_smile(np.array([k]))[0], 1e-8) / T)
            rows.append({"log_moneyness": k, "T": T, "implied_volatility": iv})

    _k, _t, grid = interpolate_to_grid(pd.DataFrame(rows), method="svi")
    assert np.isfinite(grid).all()
    assert grid.min() > 0.01
