#!/usr/bin/env python
"""CLI: reproduce the volatility-forecast evaluation and write it up.

Walk-forward on SPY (default 2013–2023, three years of warm-up), at 5- and
21-trading-day horizons:

1. every core model (implied, GARCH, GJR-GARCH, HAR, HAR + implied,
   HAR + surface, gradient boosting), plus LSTM and LSTM-GARCH with --lstm
   (needs the [experimental] extra; ~15 minutes);
2. QLIKE by VIX regime;
3. surface-feature groups added one at a time to HAR + implied;
4. univariate predictive regressions of the features on forward returns
   and forward variance-swap P&L.

Writes a Markdown report (default docs/forecast_evaluation.md).

Usage:
    python scripts/evaluate_forecasts.py
    python scripts/evaluate_forecasts.py --lstm --out docs/forecast_evaluation.md
"""

import logging
import sys
import time
import warnings
from pathlib import Path

import click

# --lstm imports from experimental/, which is not part of the installed
# package; make the repo root importable when run as `python scripts/...`.
_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

logging.basicConfig(level=logging.WARNING, stream=sys.stdout)


def _md(df, floatfmt=".4f") -> str:
    """A DataFrame as a Markdown table (no tabulate dependency)."""
    cols = [df.index.name or ""] + [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for idx, row in df.iterrows():
        cells = [str(idx)] + [
            ("" if v != v else format(v, floatfmt)) if isinstance(v, float) else str(v)
            for v in row.to_numpy()
        ]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


@click.command()
@click.option("--ticker", default="SPY", show_default=True)
@click.option("--start", default="2013-01-01", show_default=True, help="First forecast date")
@click.option("--end", default="2023-12-29", show_default=True, help="Last forecast date")
@click.option("--lstm", is_flag=True, help="Also run LSTM and LSTM-GARCH (slow; needs torch)")
@click.option("--out", default="docs/forecast_evaluation.md", show_default=True)
def main(ticker, start, end, lstm, out):
    """Run the evaluation and write the report."""
    from pathlib import Path

    import numpy as np
    import pandas as pd

    from src.forecast.dataset import build_dataset
    from src.forecast.evaluate import by_regime, compare, predictive_regression
    from src.forecast.models import (HAR_TERMS, IV_TERMS, SURFACE_TERMS, LogLinear,
                                     har_iv, standard_models)

    warnings.filterwarnings("ignore")
    ds = build_dataset(ticker)
    say = lambda m: click.echo(m, err=True)
    parts = [f"# Volatility forecast evaluation — {ticker}\n",
             f"Walk-forward, {start} to {end}, monthly refits; each refit trains only "
             "on targets already observed. Lower QLIKE is better; `dm_stat` > 0 "
             "means the model beats the baseline (Diebold-Mariano, Newey-West with "
             "h lags). Vol metrics are in vol points.\n",
             "Generated by `scripts/evaluate_forecasts.py`.\n"]

    factories = dict(standard_models())
    if lstm:
        from experimental.forecast.lstm import lstm as lstm_f, lstm_garch

        factories.update({"LSTM": lstm_f, "LSTM-GARCH": lstm_garch})

    vix = ds["mkt_vix"]
    regime = pd.cut(vix, [0, 15, 25, 200], labels=["VIX<15", "VIX 15-25", "VIX>25"])
    for h in (5, 21):
        t0 = time.time()
        fc, rep = compare(ds, factories, h, start=start, end=end,
                          progress=lambda n, h=h: say(f"h={h}: {n} ({time.time() - t0:.0f}s)"))
        parts += [f"\n## {h}-day horizon ({len(fc.dropna())} common days)\n",
                  _md(rep.sort_values("qlike").drop(columns="n")),
                  "\nQLIKE by VIX regime at the forecast date:\n",
                  _md(by_regime(fc, regime).T)]

        groups = {"skew (rr25, bf25, ATM skew)": ["rr25_30d", "bf25_30d", "atm_skew_30d"],
                  "term structure (91d VS, 30→91 spread, VIX3M/VIX)": ["log_vs_91d", "ts_30_91", "log_vix_ts"],
                  "vol-of-vol and tail (VVIX, CBOE SKEW)": ["log_vvix", "mkt_skew"],
                  "variance risk premium": ["vrp_30d"]}
        facs = {"HAR + implied": har_iv}
        for g, cols in groups.items():
            facs[f"+ {g}"] = (lambda cols=cols, g=g: LogLinear(
                g, {**HAR_TERMS, **IV_TERMS, **{c: SURFACE_TERMS[c] for c in cols}}, alpha=5.0))
        say(f"h={h}: feature-group ablation")
        _, abl = compare(ds, facs, h, start=start, end=end, baseline="HAR + implied")
        parts += ["\nSurface-feature groups added to HAR + implied:\n",
                  _md(abl[["qlike", "r2_log", "dm_stat", "dm_p"]])]

    # ── Other targets ────────────────────────────────────────────────────
    span = ds[(ds.index >= "2010-01-01") & (ds.index <= end)]
    fwd_ret = span["ret"][::-1].rolling(21).sum()[::-1].shift(-1)
    targets = {"forward 21d log return": fwd_ret,
               "forward variance-swap P&L, short vol (relative)":
                   (span["vs_30d"] ** 2 - span["y_21"]) / span["vs_30d"] ** 2}
    feats = {"vs_30d": span.vs_30d, "ts_7_30": span.ts_7_30, "ts_30_91": span.ts_30_91,
             "rr25_30d": span.rr25_30d, "bf25_30d": span.bf25_30d,
             "atm_skew_30d": span.atm_skew_30d, "vrp_30d": span.vrp_30d,
             "VIX3M/VIX": span.mkt_vix3m / span.mkt_vix, "VVIX": span.mkt_vvix,
             "CBOE SKEW": span.mkt_skew}
    n_tests = len(feats) * len(targets)
    parts.append(f"\n## Other targets (univariate, 2010 to {end}, 21-day overlap)\n"
                 f"Bonferroni over {n_tests} tests.\n")
    for tname, y in targets.items():
        rows = {f: predictive_regression(x, y, 21) for f, x in feats.items()}
        tbl = pd.DataFrame(rows).T
        tbl["bonferroni_p"] = (tbl["p"] * n_tests).clip(upper=1.0)
        tbl.index.name = "feature"
        parts += [f"\n### {tname}\n", _md(tbl.sort_values("p").drop(columns="n"))]

    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text("\n".join(parts) + "\n", encoding="utf-8")
    click.echo(f"Report written to {out}")


if __name__ == "__main__":
    main()
