#!/usr/bin/env python
"""CLI: does pricing earnings separately improve single-stock vol forecasts?

Two walk-forward comparisons, scored by QLIKE on realised variance, with
Diebold-Mariano tests (Newey-West, lag = horizon):

A. **Long sample, no options** (2013 onwards, every single stock with
   earnings dates): plain HAR against HAR on ex-earnings inputs plus the
   *historical* average earnings move whenever a release falls in the
   window.  Thousands of event windows, so this tests the mechanism.
B. **Live sample, with options** (Feb 2026 onwards, the single stocks with
   surfaces): the production HAR + implied model against the same model on
   ex-earnings inputs plus the *implied* earnings move from the surface,
   and against raw implied vol.  Few events, so read it as a sanity check.

Both pool across tickers like production.  Writes a Markdown report
(default docs/earnings_evaluation.md).

Usage:
    python scripts/evaluate_earnings.py
"""

import logging
import sys
from pathlib import Path

import click

logging.basicConfig(level=logging.WARNING, stream=sys.stdout)


def _md(df, floatfmt=".4f") -> str:
    cols = [df.index.name or ""] + [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for idx, row in df.iterrows():
        cells = [str(idx)] + [
            ("" if v != v else format(v, floatfmt)) if isinstance(v, float) else str(v)
            for v in row.to_numpy()
        ]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def _compare(base, model, label_base, label_model, raw_implied=False):
    """QLIKE of two forecast frames on common rows, all / event / no-event windows."""
    import numpy as np
    import pandas as pd

    from src.forecast.evaluate import diebold_mariano, qlike_series

    rows = []
    for h in sorted(model["horizon"].unique()):
        key = ["ticker", "date"]
        b = base[base["horizon"] == h].set_index(key)
        m = model[model["horizon"] == h].set_index(key)
        idx = b.index.intersection(m.index)
        b, m = b.loc[idx], m.loc[idx]
        y = m["realised_vol"] ** 2
        ok = y.notna() & (y > 0)
        b, m, y = b[ok], m[ok], y[ok]
        fc = {label_base: b["forecast_vol"] ** 2, label_model: m["forecast_vol"] ** 2}
        if raw_implied:
            fc["Implied (raw)"] = m["implied_vol"] ** 2
        ev = m["earnings_in_window"].astype(bool)
        for name, mask in (("all", slice(None)), ("earnings in window", ev),
                           ("no earnings", ~ev)):
            yy = y[mask]
            if len(yy) == 0:
                continue
            row = {"horizon": f"{h}d", "windows": name, "n": int(len(yy))}
            losses = {k: qlike_series(yy, f[mask]) for k, f in fc.items()}
            for k, l in losses.items():
                row[k] = float(l.mean())
            # DM on the date-averaged loss differential (tickers overlap in time).
            d = (losses[label_base] - losses[label_model]).groupby(level="date").mean()
            stat, p = diebold_mariano(d, pd.Series(0.0, index=d.index), lag=h)
            row["DM stat"], row["p"] = stat, p
            rows.append(row)
    return pd.DataFrame(rows).set_index("horizon")


@click.command()
@click.option("--start", default="2013-01-01", show_default=True)
@click.option("--live-start", default="2026-02-01", show_default=True)
@click.option("--out", default="docs/earnings_evaluation.md", show_default=True)
def main(start, live_start, out):
    """Run both comparisons and write the report."""
    import pandas as pd

    from src.data.events import load_earnings
    from src.forecast.forecaster import build_forecasts

    stocks = sorted(load_earnings()["ticker"].unique())
    if not stocks:
        raise SystemExit("No earnings dates; run scripts/fetch_earnings.py first.")

    click.echo(f"A. HAR vs earnings-adjusted HAR on {len(stocks)} stocks from {start} ...")
    har = build_forecasts(stocks, start=start, use_implied=False, event_adjusted=False)
    har_ev = build_forecasts(stocks, start=start, use_implied=False, event_adjusted=True)
    a = _compare(har, har_ev, "HAR", "HAR, earnings-adjusted")

    click.echo("B. HAR + implied vs earnings-adjusted, live sample ...")
    prod = build_forecasts(event_adjusted=False)
    prod_ev = build_forecasts(event_adjusted=True)
    live = lambda f: f[f["ticker"].isin(stocks) & (f["date"] >= live_start)]
    b = _compare(live(prod), live(prod_ev), "HAR + implied", "earnings-adjusted",
                 raw_implied=True)
    pb = live(prod_ev)
    pb = pb[pb["realised_vol"].notna()]
    n_events = (pb[pb["earnings_in_window"]].groupby("ticker")["earnings_move"].nunique())

    parts = [
        "# Earnings-aware volatility forecasts",
        "",
        "Generated by `scripts/evaluate_earnings.py`. QLIKE on realised variance "
        "(lower is better). DM stat > 0 means the earnings-adjusted model is better; "
        "it is computed on the loss differential averaged across tickers per date, "
        "with Newey-West lag = horizon.",
        "",
        f"## A. Long sample without options ({start} onwards)",
        "",
        f"Pooled across {len(stocks)} stocks ({', '.join(stocks)}). The adjustment "
        "uses each stock's historical average excess earnings-day move.",
        "",
        _md(a),
        "",
        f"## B. Live sample with options ({live_start} onwards)",
        "",
        "Single stocks with surfaces and a closed forecast window: "
        f"{', '.join(sorted(pb['ticker'].unique()))}. Event windows by ticker: "
        f"{n_events.to_dict()}. The adjustment uses the implied earnings move.",
        "",
        _md(b),
        "",
    ]
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text("\n".join(parts) + "\n", encoding="utf-8")
    with pd.option_context("display.width", 200):
        click.echo(a.round(4).to_string())
        click.echo(b.round(4).to_string())
    click.echo(f"Report -> {out}")


if __name__ == "__main__":
    main()
