#!/usr/bin/env python
"""CLI: which features predict what, ticker by ticker and by asset class?

The forecast evaluation found that on SPY nothing beyond the implied-vol
level helps.  This repeats the question across the whole universe, where
skew, term structure, macro and earnings features may matter more.

For every ticker with at least ``--min-obs`` rows, each feature gets a
univariate predictive regression (Newey-West t-stats for the overlapping
21-day windows) on three targets:

* **excess variance**: ``log(realised variance over the next 21 sessions)
  − log(30d variance-swap variance)``.  A feature that predicts this adds
  information beyond the implied-vol level.
* **forward return** over 21 sessions;
* **implied-vol change**: change in 30d ATM vol over 21 sessions.

Results are summarised per asset class: the median slope (per one sd of
the feature), how many tickers have |t| > 2, and how many share the
median's sign.  Per-ticker t-stats overlap in time, so treat the counts as
descriptive, not as a joint test.  Writes docs/feature_study.md.

Re-run once the live corpus has about a year of history across tickers
(early 2027); with a few months the results are indicative only.

Usage:
    python scripts/feature_study.py
    python scripts/feature_study.py --min-obs 60 --start 2026-02-01
"""

import logging
import sys
from pathlib import Path

import click

logging.basicConfig(level=logging.WARNING, stream=sys.stdout)

FEATURES = [
    "rr25_30d", "bf25_30d", "atm_skew_30d", "ts_7_30", "ts_30_91", "ts_30_365",
    "vrp_30d", "atm_30d_pct252", "atm_30d_d5", "rr25_30d_d5",
    "mkt_vvix", "mkt_skew", "mkt_move", "macro_hy_oas", "macro_nfci",
    "earn_days_to", "earn_implied_move",
]
H = 21


def _md(df, floatfmt=".3f") -> str:
    cols = [df.index.name or ""] + [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for idx, *values in df.itertuples(name=None):   # keeps each column's dtype
        cells = [str(idx)] + [("" if v != v else format(v, floatfmt)) if isinstance(v, float)
                              else str(v) for v in values]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


@click.command()
@click.option("--start", default=None, help="First feature date (default: all history)")
@click.option("--min-obs", default=100, show_default=True,
              help="Minimum rows with a closed 21-day window per ticker")
@click.option("--out", default="docs/feature_study.md", show_default=True)
def main(start, min_obs, out):
    """Run the study and write the report."""
    import numpy as np
    import pandas as pd

    from src.data.universe import GROUPS, group_of
    from src.features.labels import training_frame
    from src.forecast.evaluate import predictive_regression

    df = training_frame(horizons=(H,), start=start)
    df["excess_var"] = np.log(df[f"label_rv_{H}"] ** 2) - np.log(df["vs_30d"] ** 2)
    targets = {"excess variance": "excess_var", "forward return": f"label_ret_{H}",
               "implied-vol change": f"label_atm30_chg_{H}"}

    rows = []
    for t, g in df.groupby("ticker"):
        g = g.set_index("date").sort_index()
        for tname, tcol in targets.items():
            y = g[tcol].replace([np.inf, -np.inf], np.nan)
            for f in FEATURES:
                if f not in g:
                    continue
                d = pd.concat([g[f], y], axis=1).dropna()
                if len(d) < min_obs or d.iloc[:, 0].std() == 0:
                    continue
                r = predictive_regression(d.iloc[:, 0], d.iloc[:, 1], H)
                rows.append({"ticker": t, "group": group_of(t), "target": tname,
                             "feature": f, **r})
    res = pd.DataFrame(rows)
    if res.empty:
        raise SystemExit(f"No ticker has {min_obs} usable rows yet.")

    def summarise(x):
        med = x["slope_per_sd"].median()
        return pd.Series({"tickers": len(x), "median slope/sd": med,
                          "|t|>2": int((x["t"].abs() > 2).sum()),
                          "same sign": int((np.sign(x["slope_per_sd"]) == np.sign(med)).sum()),
                          "median R²": x["r2"].median()})

    summary = res.groupby(["target", "group", "feature"]).apply(summarise, include_groups=False)
    coverage = res.groupby("ticker")["n"].max().rename("rows").to_frame()
    coverage["group"] = [group_of(t) for t in coverage.index]

    parts = ["# Feature study across tickers", "",
             "Generated by `scripts/feature_study.py`. Univariate predictive regressions "
             f"over {H}-session windows, Newey-West t-stats; slopes are per one standard "
             "deviation of the feature, in the target's units (log-variance ratio, log "
             "return, vol). Per-ticker tests overlap in time: the counts are descriptive.",
             "", f"Tickers with at least {min_obs} usable rows:", "",
             _md(coverage.sort_values(["group", "rows"]), ".0f"), ""]
    for tname in targets:
        if tname not in summary.index.get_level_values("target"):
            continue
        s = summary.loc[tname].reset_index()
        s.index = s["group"] + " · " + s["feature"]
        s.index.name = "group · feature"
        s = s.drop(columns=["group", "feature"])
        s = s.astype({"tickers": int, "|t|>2": int, "same sign": int})
        order = {g: i for i, g in enumerate(GROUPS)}
        s = s.iloc[sorted(range(len(s)), key=lambda i: (order.get(s.index[i].split(" · ")[0], 99),
                                                        -s["|t|>2"].iloc[i]))]
        parts += [f"## Target: {tname}", "", _md(s), ""]
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text("\n".join(parts) + "\n", encoding="utf-8")
    res.to_csv(Path(out).with_suffix(".csv"), index=False)
    click.echo(coverage.to_string())
    click.echo(f"{len(res)} regressions -> {out} (+ per-ticker CSV)")


if __name__ == "__main__":
    main()
