#!/usr/bin/env python
"""CLI: write the feature table's data contract to docs/.

Writes docs/feature_catalog.md (for people) and docs/feature_catalog.json
(for code): every column of the current feature table with its group, unit,
meaning and when it is NaN, plus its non-null share in the live table.

Usage:
    python scripts/feature_catalog.py
"""

import json
from pathlib import Path

import click


@click.command()
@click.option("--features", default="data/features/surface_features.parquet", show_default=True)
@click.option("--out-dir", default="docs", show_default=True)
def main(features, out_dir):
    """Write the catalog for the columns of *features*."""
    import pandas as pd

    from src.features.catalog import catalog, undocumented

    df = pd.read_parquet(features)
    missing = undocumented(df.columns)
    if missing:
        raise SystemExit(f"Undocumented columns (add them to src/features/catalog.py): {missing}")
    cat = catalog(df.columns)
    cat["non_null_live"] = [round(float(df[c].notna().mean()), 3) for c in cat["column"]]

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "feature_catalog.json").write_text(
        json.dumps(cat.to_dict(orient="records"), indent=1, ensure_ascii=False) + "\n", encoding="utf-8")

    lines = ["# Feature catalog", "",
             "Generated by `scripts/feature_catalog.py` from `src/features/catalog.py`. "
             "Machine-readable copy: `feature_catalog.json`.", "",
             "**Timing:** a row dated *t* uses only information available at about 16:30 ET "
             "on *t*; use it to predict anything over `(t, t+h]`. Vols are decimals "
             "(0.15 = 15%). For training labels aligned to these rows, see "
             "`src.features.labels.training_frame`.", ""]
    for group, g in cat.groupby("group", sort=False):
        lines += [f"## {group}", "", "| Column | Unit | Meaning | NaN when | Non-null (live) |",
                  "|---|---|---|---|---|"]
        for _, r in g.iterrows():
            lines.append(f"| `{r['column']}` | {r['unit']} | {r['description']} | "
                         f"{r['nan_when']} | {r['non_null_live']:.0%} |")
        lines.append("")
    (out / "feature_catalog.md").write_text("\n".join(lines), encoding="utf-8")
    click.echo(f"{len(cat)} columns -> {out / 'feature_catalog.md'}, {out / 'feature_catalog.json'}")


if __name__ == "__main__":
    main()
